name: HomeworkWorkflow
on:
  pull_request:
    types: [opened]

jobs:
  print-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          echo "My ENV_VAR is = ${{ env.ENV_VAR }}"
          echo "My ENV_SECRET is = ${{ secrets.ENV_SECRET }}"
