name: HomeworkWorkflow
on:
  pull_request:
    types: [opened]

jobs:
  print-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          echo "Environment Variable (value): $ENV_VAR"
          echo "Secret Variable (value): $ENV_SECRET"
